"""user on delete cascade

Revision ID: 672cb9fdb0d9
Revises: 92077201fe6f
Create Date: 2024-05-23 07:14:31.858794

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "672cb9fdb0d9"
down_revision: Union[str, None] = "92077201fe6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_unique_constraint(None, "tasks", ["id"])
    op.drop_constraint("tasks_user_id_fkey", "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        "tasks_user_id_fkey", "tasks", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_constraint(None, "tasks", type_="unique")
    op.alter_column("tasks", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
